
# Configuración General
"$schema" = 'https://starship.rs/config-schema.json'
# Aumenta el timeout de 500ms a 1000ms
command_timeout = 2000
scan_timeout = 100
palette = "catppuccin_mocha"

# Formato del Prompt
format = """
[░▒▓](blue)\
$os\
$directory\
[](fg:blue bg:purple)\
$git_branch\
$git_status\
[](fg:purple bg:cyan)\
$python\
$nodejs\
[](fg:cyan) \
$character"""

[os]
disabled = false
style = "bg:blue fg:base"
[os.symbols]
Windows = "󰍲 "  # Icono de Windows para Nerd Fonts

[directory]
style = "bg:blue fg:base"
format = "[ $path ]($style)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
symbol = ""
style = "bg:mauve fg:base"
format = "[[ $symbol $branch ]($style)]($style)"

[git_status]
style = "bg:purple fg:white"
format = "[[($all_status$ahead_behind )]($style)]($style)"

[python]
symbol = ""
style = "bg:cyan fg:black"
# Optimizado para uv y entornos virtuales
pyenv_prefix = "venv "
format = "[[ $symbol ($virtualenv) ]($style)]($style)"

[nodejs]
style = "bg:cyan fg:black"
format = "[[ $symbol ($version) ]($style)]($style)"

[character]
success_symbol = "[󰄛](bold green)"
error_symbol = "[󰄛](bold red)"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e22e" # O "#a6e3a1" para el verde original de Mocha
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
